
CREATE TABLE IF NOT EXISTS EXERCISE (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(255) NOT NULL,
                                        description TEXT
);


CREATE TABLE IF NOT EXISTS MUSCLE_GROUP (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            name VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS EXERCISE_MUSCLE_GROUP (
                                                     exercise_id BIGINT,
                                                     muscle_group_id BIGINT,
                                                     FOREIGN KEY (exercise_id) REFERENCES EXERCISE(id),
                                                     FOREIGN KEY (muscle_group_id) REFERENCES MUSCLE_GROUP(id)
);